echarts/urls.py
from django.urls import path
from . import views
app_name = 'echarts'
urlpatterns = [
    path('covid-19/ctmap/', views.CtView.as_view(),name = 'covid_19_ctmap'),
    path('covid-19/csmap/', views.CsView.as_view(),name = 'covid_19_csmap'),
    path('covid-19/fimap/', views.CdView.as_view(),name = 'covid_19_fimap'),
    path('covid-19/gtmap/', views.GtView.as_view(),name = 'covid_19_gtmap'),
    path('covid-19/gsmap/', views.GsView.as_view(),name = 'covid_19_gsmap'),
    path('covid-19/ftemap/', views.GdView.as_view(),name = 'covid_19_ftemap'),
    path('covid-19/',views.IndexView.as_view(),name = 'covid_19'),
    path('covid-19/update/',views.update,name = 'covid_19_update'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from echarts.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('echarts/',include('echarts.urls',namespace = 'echarts')),
    path('',IndexView.as_view(),name = 'home'),
]

echarts/models.py
from django.db import models

# Create your models here.

echarts/views.py
from django.shortcuts import render,redirect
import json
from django.http import HttpResponse
from rest_framework.views import APIView
from . import data_get
from . import data_map
import ast
# Create your views here.
def response_as_json(data):
    json_str = json.dumps(data)
    response = HttpResponse(
        json_str,
        content_type = 'application/json',
    )
    response["Access-Control-Allow-Origin"] = '*'
    return response

def json_response(data,code=200):
    data = {
        "code":code,
        "msg":"success",
        "data":data,
    }
    return response_as_json(data)

def json_error(error_string = 'error',code=500,**kwargs):
    data = {
        "code":code,
        "msg":error_string,
        "data":{},
    }
    data.update(kwargs)
    return response_as_json(data)

def plot_map(data):
    global ct_map, cs_map,fi_map,gt_map,gs_map,fte_map    
    wb_china = data_get.china_total_data(data)
    wb_global = data_get.global_total_data(data)
    ct_map, cs_map = data_map.china_total_map(wb_china)
    fi_map = data_map.china_daily_map(wb_china)
    gt_map, gs_map = data_map.global_total_map(wb_global)
    fte_map = data_map.foreign_daily_map(wb_global)
    
JsonResponse = json_response
JsonError = json_error
f = open('./echarts/covid_19.json','r',encoding = 'utf-8')
data = ast.literal_eval(f.read())
f.close()
plot_map(data)
maptype = 'ctmap'

def update(request):
    data = data_get.init()
    plot_map(data)
    return redirect('echarts:covid_19')

class CtView(APIView):
    def get(self,request,*args,**kwargs):
        global ct_map,maptype
        mathtype = request.GET.get('maptype')
        return JsonResponse(json.loads(ct_map))

class CsView(APIView):
    def get(self,request,*args,**kwargs):
        global cs_map,maptype
        mathtype = request.GET.get('maptype')
        return JsonResponse(json.loads(cs_map))

class CdView(APIView):
    def get(self,request,*args,**kwargs):
        global fi_map,maptype
        mathtype = request.GET.get('maptype')
        return JsonResponse(json.loads(fi_map))

class GtView(APIView):
    def get(self,request,*args,**kwargs):
        global gt_map,maptype
        mathtype = request.GET.get('maptype')
        return JsonResponse(json.loads(gt_map))

class GsView(APIView):
    def get(self,request,*args,**kwargs):
        global gs_map,maptype
        mathtype = request.GET.get('maptype')
        return JsonResponse(json.loads(gs_map))

class GdView(APIView):
    def get(self,request,*args,**kwargs):
        global gs_map,maptype
        mathtype = request.GET.get('maptype')
        return JsonResponse(json.loads(fte_map))

class IndexView(APIView):
    def get(self,request,*args,**kwargs):
        global maptype
        context = {'maptype':maptype}
        return render(request,'echarts/covid_19.html',context = context)

templates/echarts/covid_19.html
<!DOCTYEP html>
{% load static %}
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>疫情大数据报告</title>
    <!--script src="{% static 'echarts/layer/layer.js' %}"></script-->
    <link rel="stylesheet" href="{% static 'echarts/bootstrap/css/bootstrap.min.css' %}">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <p class="navbar-brand">疫情大数据报告</p>
        <div>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'echarts:covid_19_update' %}">更新</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'echarts:covid_19' %}">返回</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
    <script src="{% static 'echarts/jquery/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'echarts/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'echarts/js/echarts.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'echarts/js/maps/china.js' %}"></script>
    <script type="text/javascript" src="{% static 'echarts/js/maps/world.js' %}"></script>
    <script type="text/javascript" src="{% static 'echarts/bootstrap/js/bootstrap.min.js' %}"></script>
<div class="container">
    <div class="row">
        <div class="col-2">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/ljc545w/myproject" target="_blank">Github</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        国内疫情
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                        <a class="dropdown-item" href="#" onclick="show('1','2','ctmap')">累计确诊</a>
                        <a class="dropdown-item" href="#" onclick="show('1','2','csmap')">现有确诊</a>
                        <a class="dropdown-item" href="#" onclick="show('2','1','fimap')">疫情走势</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        国外疫情
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                        <a class="dropdown-item" href="#" onclick="show('1','2','gtmap')">累计确诊</a>
                        <a class="dropdown-item" href="#" onclick="show('1','2','gsmap')">现有确诊</a>
                        <a class="dropdown-item" href="#" onclick="show('2','1','ftemap')">疫情走势</a>
                    </div>
                </li>
            </ul>
        </div>
        <div class="col-9">
            <div id="map1" style="height:550px;display:none"></div>
            <div id="map2" style="height:370px;display:none"></div>
        </div>
    </div>
</div>
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; pyecharts.org 2021</p>
    </div>
</footer>
<script>
    $ (function() {
        if('{{ maptype }}' == 'fimap' || '{{ maptype }}' == 'ftemap'){
            show('2','1','{{ maptype }}');
        } else{
            show('1','2','{{ maptype }}');
        }
    }
    )
    function show(Id,nId,maptype) {
        document.getElementById("map" + Id).style.display="block";
        document.getElementById("map" + nId).style.display="none";
        var chart = echarts.init(document.getElementById("map"+Id),'write',{renderer:'canvas'});
        fetchData(chart,maptype);
    }
    function fetchData(chart,maptype) {
        $.ajax({
            type:"GET",
            url:"/echarts/covid-19/" + maptype + "?maptype=" + maptype,
            dataType:'json',
            //async:false,
            success:function (result) {
               chart.setOption(result.data);
           },
        });
    }
</script>
</body>
</html>